### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by nash169** [ros-melodic-arch/ros-melodic-actionlib-tutorials#2]
Hi,
Compiling this package I get an error about pthread of the type "undefined reference to pthread_mutexattr". 
In order to compile I had to add "-pthread" flag to cxx:
-DCMAKE_CXX_FLAGS="-pthread" to the PKGBUILD

**Comment by jwhendy** [comment]
See https://github.com/ros-melodic-arch/ros-melodic-actionlib-tutorials/issues/1

Currently two of us cannot reproduce this. If you can track down why the issue is occurring for you, we'd be happy to take a look. Currently, sadly, we can't and this it's not clear if this is an issue for your system or for all ROS users. Thus, we can't figure out if a patch is actually warranted.

**Comment by nash169** [comment]
I see. I also asked to a friend of mine to compile this pack and he didn't have any problem about this. So apparently it's something related to the system configuration. I'll let you know if I find out something about this.

Thanks
